feat(wallet): add security settings
nymtech/nym pull request #3262
Opened 2023-03-31 07:02 UTC by doums

# Description

Closes: #2275

2023-04-06 08:49 UTC, octol requested changes

2023-04-06 08:49 UTC, octol commented on nym-wallet/src-tauri/src/wallet_storage/mod.rs
> +    stored_wallet.replace_encrypted_login(new_login)?;
Maybe I'm missing it, but what happens in the case for multiple logins? Will all passwords be updated? Should they?

Also, would be be good with some unit tests for these cases

2023-04-06 08:49 UTC, octol commented on nym-wallet/src-tauri/src/wallet_storage/mod.rs
> +pub(crate) fn save_login(
Imho, with overwrite = false you are effectively appending a login to a file, with overwrite = true you're not appending, but resaving existing logins already in the file. So it feels like the latter should be a separate function. Basically the first is a `.append()` and the latter is a `.for_each(mutate)`.

```
fn store_login_with_multiple_accounts()

fn re_store_all_logins()
```

2023-04-11 15:07 UTC, octol commented on nym-wallet/src-tauri/src/wallet_storage/account_data.rs
> +    pub fn reencrypt_login(
Looks good! I take it wasn't possible to call `decrypt_login` due to the lack of `mut`?

IMHO let's also do a `reencrypt_all`

2023-04-11 15:07 UTC, octol commented on nym-wallet/src-tauri/src/wallet_storage/mod.rs
> +pub(crate) fn save_encrypted_login(
"save" is fine, but I think in all the other functions "store" is used? If that's the case lets stay consistent

2023-04-11 15:07 UTC, octol commented on nym-wallet/src-tauri/src/wallet_storage/mod.rs
> +fn get_new_encrypted_login(
Can probably skip the `get_`

2023-04-11 15:07 UTC, octol commented on nym-wallet/src-tauri/src/wallet_storage/mod.rs
> +pub(crate) fn update_encrypted_login(
IMHO I think we should just reencrypt all logins, if nothing else just to keep the invariant that all logins have the same password

2023-04-11 15:07 UTC, octol commented on nym-wallet/src-tauri/src/operations/mixnet/account.rs
> +    let login_id = wallet_storage::LoginId::new(DEFAULT_LOGIN_ID.to_string());
Just skip this an re-encrypt all logins (sorry duplicate comment)

2023-04-12 10:42 UTC, octol commented on nym-wallet/src-tauri/src/wallet_storage/mod.rs
> +/// Update all logins with multiple accounts support
You update all logins, whether each of them contain multiple accounts or not. The current wording makes it sounds like you're updating only the ones with multiple accounts support

2023-04-12 10:42 UTC, octol commented on nym-wallet/src-tauri/src/wallet_storage/mod.rs
> +    let filepath = store_dir.join(WALLET_INFO_FILENAME);
Just check if it exists? If you try to update something that doesn't exists then that seems like an error?

2023-04-12 10:42 UTC, octol commented on nym-wallet/src-tauri/src/wallet_storage/mod.rs
> +    #[should_panic]
Avoid panic if you can, instead check that you get the correct error type

2023-04-12 10:42 UTC, octol commented on nym-wallet/src-tauri/src/wallet_storage/mod.rs
> +        update_encrypted_logins_at_file(&wallet_file, &wrong_password, &new_password).unwrap();
If this line is expected to panic, just unwrap_err and assert on the error type

2023-04-12 10:42 UTC, octol commented on nym-wallet/src-tauri/src/wallet_storage/mod.rs
> +    #[should_panic]
Same, remove pls

2023-04-12 11:39 UTC, octol commented on nym-wallet/src-tauri/src/wallet_storage/mod.rs
> +        // Store the first account
"Store the first login with an account"

2023-04-12 11:39 UTC, octol commented on nym-wallet/src-tauri/src/wallet_storage/mod.rs
> +        // Add an extra account
"Store a second login, also with an account"

2023-04-13 12:10 UTC, octol reviewed
Rust parts approved

2023-04-13 12:11 UTC, octol approved these changes

2023-04-17 09:55 UTC, gala1234 approved these changes
Looks good for me

2023-04-17 14:36 UTC, merged