Feature/mixfetch disconnect
nymtech/nym pull request #3890
Opened 2023-09-14 15:54 UTC by jstuczyn

# Description

Closes:  https://github.com/nymtech/nym/issues/3889

# Checklist:

- [ ] added a changelog entry to `CHANGELOG.md`

2023-09-15 13:18 UTC, jstuczyn commented
@mmsinclair afaik, to fix CI we might have to release another release candidate of mixfetch

2023-09-19 13:47 UTC, mmsinclair requested changes
Nice, only one small syntax thing to change.

And I want to add an extra commit that uses the `window` event that fires before it is unloaded: https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event#usage_notes

2023-09-19 13:47 UTC, mmsinclair commented on sdk/typescript/packages/mix-fetch/src/index.ts
> +    return Promise.reject(new Error("mixFetch hasn't been setup"));
You either need to wrap the whole method in `new Promise((resolve, reject) => ...)` or you can just throw an error:

```suggestion
    throw new Error("mixFetch hasn't been setup");
```

Typescript transpiles the `throw` part into a `reject(new Error(...))`.

2023-09-21 14:16 UTC, mmsinclair commented on sdk/typescript/packages/mix-fetch/src/index.ts
> +    await disconnectMixFetch();
I think it needs this to work:

```suggestion
    await window.__mixFetchGlobal.disconnectMixFetch();
```

2023-09-22 09:25 UTC, mmsinclair approved these changes

2023-09-22 09:25 UTC, merged