[DOC/operators]: Legal Forum - Community landing pages stub
nymtech/nym pull request #4365
Opened 2024-01-31 11:39 UTC by serinko

# Description

Simplifying process of adding info with an aim to incentivise operators creating direct PRs. 

- [x] Community Counsel page
- [x] Landing pages stub
- [x] Cleaner "how to add info"

2024-01-31 12:40 UTC, mfahampshire requested changes

2024-01-31 12:40 UTC, mfahampshire commented on documentation/operators/src/legal/community-counsel.md
> +To add your information to this book, you can create a PR directly to our [repository](https://github.com/nymtech/nym/tree/develop/documentation/operators/src/legal), than ping the admins in the [Leg
* 'then' not 'than' 
* do you think we need to write for them to ping us? Wont we just see the PRs?

2024-01-31 12:40 UTC, mfahampshire commented on documentation/operators/src/legal/community-counsel.md
> +1. Write down your legal findings, suggestions, communication templates, FAQ in a text editor (Soon we will share a template)
'soon' not 'Soon'

2024-01-31 12:40 UTC, mfahampshire commented on documentation/operators/src/legal/community-counsel.md
> +# choose a descriptive and consise name without using <>
* i would add an example command here
* you can perform both of these commands in one with `git checkout -b <branchname>`

2024-01-31 12:40 UTC, mfahampshire commented on documentation/operators/src/legal/community-counsel.md
> +5. Don't change anything in `SUMMARY.md`, the admins will do it when merging
write this in bold imo

2024-01-31 12:40 UTC, mfahampshire commented on documentation/operators/src/legal/exit-gateway.md
> +## How to add content
why are we doubling this info? i feel like we _could_ make it its own page and refer to it, similar to how we have with the maintenance? no strict need to though, more a thought. 

also - see above comments on previous 'how to add' text

2024-01-31 12:40 UTC, mfahampshire commented on documentation/operators/src/legal/landing-pages.md
> +Exit Gateway landing page is a great and transparent way to prevent uneducated people creating problems by providing them with basic facts, links to laws and regulations on a given topic as well as o
'uneducated people' sounds a bit harsh imo

2024-01-31 12:45 UTC, serinko commented on documentation/operators/src/legal/landing-pages.md
> +Exit Gateway landing page is a great and transparent way to prevent uneducated people creating problems by providing them with basic facts, links to laws and regulations on a given topic as well as o
lol, true, will redo :D

2024-01-31 16:30 UTC, serinko commented on documentation/operators/src/legal/community-counsel.md
> +To add your information to this book, you can create a PR directly to our [repository](https://github.com/nymtech/nym/tree/develop/documentation/operators/src/legal), than ping the admins in the [Leg
removed extra

2024-01-31 16:30 UTC, serinko commented on documentation/operators/src/legal/community-counsel.md
> +1. Write down your legal findings, suggestions, communication templates, FAQ in a text editor (Soon we will share a template)
removed

2024-01-31 16:31 UTC, serinko commented on documentation/operators/src/legal/community-counsel.md
> +# choose a descriptive and consise name without using <>
done

2024-01-31 16:31 UTC, serinko commented on documentation/operators/src/legal/community-counsel.md
> +5. Don't change anything in `SUMMARY.md`, the admins will do it when merging
done

2024-01-31 16:31 UTC, serinko commented on documentation/operators/src/legal/exit-gateway.md
> +## How to add content
done

2024-01-31 16:31 UTC, serinko commented on documentation/operators/src/legal/landing-pages.md
> +Exit Gateway landing page is a great and transparent way to prevent uneducated people creating problems by providing them with basic facts, links to laws and regulations on a given topic as well as o
done

2024-02-01 07:41 UTC, mfahampshire approved these changes

2024-02-01 07:41 UTC, merged