Max/new mdbook theme
nymtech/nym pull request #4377
Opened 2024-02-07 12:58 UTC by mfahampshire

# Description

theme overhaul for mdbook documentation

2024-02-07 16:53 UTC, gala1234 approved these changes
Looks good for me

2024-02-08 09:22 UTC, serinko requested changes
This is some amazing job. Taking the books to the top floor mate! Appreciate it.

2024-02-08 09:22 UTC, serinko commented on documentation/dev-portal/book.toml
> +multilingual = false # for the moment - ideally work on chinese, brazillian, spanish next
I would maybe note "brazilian" as "portuguese" so ppl don't call us on it

2024-02-08 09:45 UTC, serinko approved these changes

2024-02-08 10:02 UTC, merged