Max/dev portal update
nymtech/nym pull request #4696
Opened 2024-07-05 15:38 UTC by mfahampshire

todo
- [ ] get `docs/` build working with now-dead links 
- [ ] double check `serve` 
- [ ] add a 'general dev approach overview' page to `dev-portal` under the `client-overview`: how to approach piping traffic through
- [ ] add `zcash-rpc-demo` to the examples

2024-07-09 14:59 UTC, serinko requested changes

2024-07-09 14:59 UTC, serinko commented on documentation/dev-portal/src/clients/socks5/usage.md
> +- ircd chat
darkfi sunset ircd for new darkirc. We dont have integration working for it yet, should be taken away for now.

2024-07-09 14:59 UTC, serinko commented on documentation/dev-portal/src/examples/custom-services.md
>  - PasteNym is a private pastebin alternative. It involves a browser-based frontend utilising the Typescript SDK and a Python-based backend service communicating with a standalone Nym Websocket Client
I am not sure if it works at all tbh. Haven't checked, but they stopped development on it.

2024-07-10 10:41 UTC, mfahampshire commented on documentation/dev-portal/src/clients/socks5/usage.md
> +- ircd chat
good point - will add comment to show this.

2024-07-10 10:57 UTC, serinko approved these changes

2024-07-10 11:54 UTC, merged