Social Icons & Dark Mode selector
nymtech/nym pull request #838
Opened 2021-10-21 13:11 UTC by Aid19801

1. Removed responsive Dark/Light on drawer SVG icons. That whole section stays same colour regardless of light/dark mode, as per designs.
2. Responsive Footer - shows Socials if mobile.
3. Socials - collection of Telegram, Github, Twitter
4. Light/Dark switch - moved from Drawer to Appbar; changes to smaller icon on mobile, as per (updated) designs. Note TS issue with onClick type. Tried defining it to reflect the `() => void | undefined` but i must be missing something.

2021-10-22 13:52 UTC, fmtabbara commented on explorer/src/components/Nav.tsx
> +          <List sx={{ pt: 0, pb: 0 }}>
I think the List component has a `dense` property. Might achieve the same thing

2021-10-22 14:44 UTC, Aid19801 commented on explorer/src/components/Nav.tsx
> +          <List sx={{ pt: 0, pb: 0 }}>
It does do similar but leaves padding top which i'd have to `sx={{..` to get rid of anyway so may just leave as is🤷

2021-10-22 16:11 UTC, fmtabbara requested changes

2021-10-22 16:11 UTC, fmtabbara commented on explorer/src/components/Footer.tsx
> +    <>
don't think the fragment is needed

2021-10-22 16:11 UTC, fmtabbara commented on explorer/src/components/Nav.tsx
> +    <>
Is this fragment needed?

2021-10-22 16:11 UTC, fmtabbara commented on explorer/src/components/Socials.tsx
> +          {disableDarkMode && <TelegramSVGDark />}
Might be better so have a single SVG component that takes a prop to tell it whether to display as light or dark?
`<TelegramSVG dark/>` would be dark and <TelegramSVG /> would be light.

2021-10-22 16:11 UTC, fmtabbara commented on explorer/src/components/Socials.tsx
> +              background: hoverEffect ? 'rgba(242, 242, 242, 0.08)' : 'none',
There's  a component called `IconButton` in mui that will give the the same effect. I would look at rebuilding these as a set of IconButtons in a Box.

2021-10-22 16:11 UTC, fmtabbara commented on explorer/src/components/Socials.tsx
> +          {!disableDarkMode && mode !== 'dark' && <TwitterSVGLight />}
Refactoring as suggested above would mean this becomes a one-liner
`<TwitterSVG dark={mode === dark && !disabldDarkMode} />`

2021-10-22 16:11 UTC, fmtabbara commented on explorer/src/components/Socials.tsx
> +        </ListItem>
As above

2021-10-22 16:11 UTC, fmtabbara commented on explorer/src/components/Nav.tsx
> +                key={i}
Needs fixing

2021-10-24 06:23 UTC, Aid19801 commented on explorer/src/components/Socials.tsx
> +          {disableDarkMode && <TelegramSVGDark />}
I've got around this by adding `disableDarkMode` to Socials. Now they respond to dark mode in the Footer (correct) but remain static for Nav (as per Figma).

2021-10-24 06:25 UTC, Aid19801 commented on explorer/src/components/Socials.tsx
> +              background: hoverEffect ? 'rgba(242, 242, 242, 0.08)' : 'none',
Yep, i took this effect from that component and added it manually, after i'd started using ListItem instead of IconButton. I'm back to IconButton now for the reasons covered in our chat. But i do need to re-add the external links so will see how that goes..

2021-10-24 06:36 UTC, Aid19801 commented on explorer/src/components/Socials.tsx
> +              background: hoverEffect ? 'rgba(242, 242, 242, 0.08)' : 'none',
Ok done.

2021-10-24 06:38 UTC, Aid19801 commented on explorer/src/components/Nav.tsx
> +                key={i}
Nav will be separate to Social Icons / Dark Mode. Fixing and refactoring nav, orange bar etc on new `nav-changes` branch.

2021-11-01 13:19 UTC, mmsinclair commented
The duplication in the SVG files can be removed by using the `useTheme` hook:

```js
import { useTheme } from '@mui/material/styles';
import * as React from 'react';

export const TelegramSVG: React.FC = () => {
  const theme = useTheme();
  return (
    <svg
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g clipPath="url(#clip0_661:426)">
        <path
          d="M12.4 24C19.029 24 24.4 18.629 24.4 12C24.4 5.371 19.029 0 12.4 0C5.77102 0 0.400024 5.371 0.400024 12C0.400024 18.629 5.77102 24 12.4 24ZM5.89102 11.74L17.461 7.279C17.998 7.085 18.467 7.41 18.293 8.222L18.294 8.221L16.324 17.502C16.178 18.16 15.787 18.32 15.24 18.01L12.24 15.799L10.793 17.193C10.633 17.353 10.498 17.488 10.188 17.488L10.401 14.435L15.961 9.412C16.203 9.199 15.907 9.079 15.588 9.291L8.71702 13.617L5.75502 12.693C5.11202 12.489 5.09802 12.05 5.89102 11.74Z"
          fill={theme.palette.text.primary}  <-----------------------------
        />
      </g>
      <defs>
        <clipPath id="clip0_661:426">
          <rect
            width="24"
            height="24"
            fill={theme.palette.background.default} <-----------------------------
            transform="translate(0.400024)"
          />
        </clipPath>
      </defs>
    </svg>
  );
};
```

Once these have been replaced, I'll approve this PR

2021-11-01 14:02 UTC, mmsinclair approved these changes

2021-11-01 14:02 UTC, mmsinclair commented on explorer/src/icons/OverviewSVG.tsx
> +  const color = theme.palette.primary.light;
😀  much better!

2021-11-01 14:11 UTC, merged