Mixnode Detail Alignment
nymtech/nym pull request #845
Opened 2021-10-25 14:15 UTC by Aid19801

1. styles.css override - no offered way to adjust padding on that one specific `TitleContainer` div, which is putting the header out of alignment with the cells.
2. Added `flex: 1` (mui doc'd approach) to the _non_ word-wrapping headers in DataGrid. This helps them to space out more responsively, as per Figma designs.
3. added `height: 100%` to ContentCard so reuseable cards like those in Mixnode Detail page match the height of the grid item and thus the container row. This generates the expected alignment.
4. Adjustments to margin/padding to keep the same spacing in between Detail page cards.

2021-10-26 08:15 UTC, mmsinclair requested changes
The global theme override will affect all data grids - are you sure about this?

2021-10-26 08:15 UTC, mmsinclair commented on explorer/src/styles.css
> +    padding-left: 0;
This looks to me like it would apply everywhere?

If not, then `.MuiDataGrid-override` would be best, and apply it where it is needed.

2021-10-26 08:16 UTC, mmsinclair commented
Are you sure this should be a data grid and not a plain table?

![image](https://user-images.githubusercontent.com/14054343/138836562-5e030bec-9ddd-492e-82cc-118e95eee881.png)

It has all the chrome to sort and select columns. Wouldn't a table component be better?

2021-10-26 11:24 UTC, Aid19801 commented on explorer/src/styles.css
> +    padding-left: 0;
The issue we have is we can't add a classname to that one specific header `div`. 

The div we need to kill the padding on is `.MuiDataGrid-columnHeaderTitleContainer` 

Even with their doc'd customization, ie handing the grid my `<CustomColumnHeading />` component - the div it places that _inside_ is the one we need to adjust.

So i can either override the TitleContainer myself in `styles.css` or i can counter it by styling the CustomColumnHeading with `margin-left: -6px;`. I don't normally go into minus figures though. Your call.

2021-10-26 16:18 UTC, Aid19801 commented
> Are you sure this should be a data grid and not a plain table?
> 
> ![image](https://user-images.githubusercontent.com/14054343/138836562-5e030bec-9ddd-492e-82cc-118e95eee881.png)
> 
> It has all the chrome to sort and select columns. Wouldn't a table component be better?

Yes, as discussed can switch that out in PR separate to the alignment work

2021-10-28 12:04 UTC, mmsinclair requested changes

2021-10-28 12:04 UTC, mmsinclair commented on explorer/src/styles.css
> +    padding-left: 0;
This is where that style is being applied:

![image](https://user-images.githubusercontent.com/14054343/139250994-65523b31-f357-4df3-8f2b-87f345fa7558.png)

The DOM looks like this:

![image](https://user-images.githubusercontent.com/14054343/139251201-16cd0558-0e70-4284-9a95-1999c3774b6b.png)

and 

![image](https://user-images.githubusercontent.com/14054343/139251319-186c9643-6795-451d-9fde-e0bef705ef81.png)

So the selector could be `div div.MuiDataGrid-root div.MuiDataGrid-root-override .MuiDataGrid-columnHeaderTitleContainer`

And the React component (https://github.com/nymtech/nym/blob/71ffbcdb4e3bc4e62be8af102f6ee0a89c183fc2/explorer/src/pages/Mixnodes/index.tsx#L166) would now be:

```
        <Grid container className="MuiDataGrid-root-override">
```

Then those overrides **only** apply to that particular instance of the grid and not all of them.

2021-10-28 12:04 UTC, mmsinclair commented on explorer/src/styles.css
> +    padding-left: 0;
So, the question is:

1. do you want that override to apply to all `MuiDataGrid` instances?
2. is it only the one in the mix node details page?

For option 1, what you have is good. Otherwise you need something is to constrain it to only that instance.

2021-11-01 13:22 UTC, mmsinclair approved these changes
Approving on the understanding that the MUI Data Grid header changes apply everywhere

2021-11-01 14:23 UTC, merged