Feature/ts client update
nymtech/nym pull request #956
Opened 2021-12-13 15:37 UTC by jstuczyn

This PR updates our TypeScript client to restore functionalities of being able to query our contract, validator API as well as send transactions such as bonding mixnodes.

Addresses https://github.com/nymtech/team-core/issues/35

2021-12-15 11:15 UTC, mmsinclair requested changes
Generally looking good, only a couple of minor things:

- can tidy up bits of the syntax (I'm being a little pedantic with those changes, but I feel they produce less code)
- I'll add a commit with `eslint` or `prettier` afterwards because the files could do with some consistency on formatting and it has good suggestions for TS and general code structure (it ain't a clippy but it is ok)

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/caches/gateways.ts
> -        for (;;) {
```suggestion
        while(true) {
```

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/caches/mixnodes.ts
> -        for (;;) {
```suggestion
        while(true) {
```

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/caches/mixnodes.ts
> -    async refreshValidatorAPIMixNodes(urls: string[]): Promise<MixNodeBond[]> {
Is the purpose of the `for` loop to try all validators and return the first valid response?

If so, then you need a `try {..} catch() {...}` around the `await axios.get(..)` because if the first validator fails to respond the method will return with a rejected promise.

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/caches/mixnodes.ts
> -            const response = await axios.get(validator_api_url.toString());
```suggestion
            try {
              const response = await axios.get(validator_api_url.toString());
            } catch(e) {
              console.warn(`Validator ${url} returned ${e.message}, so trying the next validator...`);
              continue;
            }
```

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/index.ts
> +        for (; ;) {
```suggestion
        while(true) {
```

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/index.ts
> +        for (; ;) {
```suggestion
        while(true) {
```

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/index.ts
>          for (; ;) {
```suggestion
        while(true)
```

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/index.ts
> +        for (; ;) {
```suggestion
        while(true)
```

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/index.ts
>          for (; ;) {
```suggestion
        while(true)
```

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/index.ts
> +    public async send(recipientAddress: string, coins: readonly Coin[], fee?: StdFee | "auto" | number, memo?: string): Promise<DeliverTxResponse> {
```suggestion
    public async send(recipientAddress: string, coins: readonly Coin[], fee?: StdFee | "auto" | number = "auto", memo?: string): Promise<DeliverTxResponse> {
```

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/index.ts
> +        }
Remove and set default argument value in function declaration above

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/index.ts
>          }
Same as above, use default argument value

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/index.ts
>          }
Use default argument value

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/index.ts
>          }
Use default argument value

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/index.ts
>          }
Use default argument value

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/signing-client.ts
> +export interface ICosmWasmSigning {
`fee` is not mandatory in most of these methods, but for ISigningClient it is - was that what you were intending?

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/signing-client.ts
> +        }
Use default argument value instead

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/signing-client.ts
> +        }
Use default argument value instead

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/signing-client.ts
> +        }
Use default argument value instead

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/signing-client.ts
> +        }
Use default argument value instead

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/signing-client.ts
> +        }
Use default argument value instead

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/signing-client.ts
> +        }
Use default argument value instead

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/signing-client.ts
> +        }
Use default argument value instead

2021-12-15 11:15 UTC, mmsinclair commented on clients/validator/src/validator-api-querier.ts
> +export default class ValidatorApiQuerier implements IValidatorApiQuery {
You could drop the returns for most of the methods

```js
        if (response.status == 200) {
            return response.data;
        }
        throw new Error("None of the provided validator APIs seem to be alive")
```

2021-12-15 13:54 UTC, jstuczyn commented on clients/validator/src/caches/gateways.ts
> -        for (;;) {
As discussed `eslint` prefers the former method

2021-12-15 13:54 UTC, jstuczyn commented on clients/validator/src/caches/mixnodes.ts
> -        for (;;) {
As discussed `eslint` prefers the former method

2021-12-15 13:54 UTC, jstuczyn commented on clients/validator/src/caches/mixnodes.ts
> -    async refreshValidatorAPIMixNodes(urls: string[]): Promise<MixNodeBond[]> {
This comment does not really apply as it refers to file that has been removed : )

2021-12-15 13:54 UTC, jstuczyn commented on clients/validator/src/caches/mixnodes.ts
> -            const response = await axios.get(validator_api_url.toString());
This comment does not really apply as it refers to file that has been removed : )

2021-12-15 14:06 UTC, jstuczyn commented on clients/validator/src/index.ts
> +        for (; ;) {
As discussed `eslint` prefers the former method

2021-12-15 14:06 UTC, jstuczyn commented on clients/validator/src/index.ts
> +        for (; ;) {
As discussed `eslint` prefers the former method

2021-12-15 14:06 UTC, jstuczyn commented on clients/validator/src/index.ts
>          for (; ;) {
As discussed `eslint` prefers the former method

2021-12-15 14:06 UTC, jstuczyn commented on clients/validator/src/index.ts
> +        for (; ;) {
As discussed `eslint` prefers the former method

2021-12-15 14:07 UTC, jstuczyn commented on clients/validator/src/index.ts
>          for (; ;) {
As discussed `eslint` prefers the former method

2021-12-15 14:08 UTC, jstuczyn commented on clients/validator/src/signing-client.ts
> +export interface ICosmWasmSigning {
I wanted our API to be as simple as possible - so that if user doesn't provide fee argument, it would default to an `"auto"`

2021-12-16 15:10 UTC, mmsinclair approved these changes

2021-12-16 15:35 UTC, merged